services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-20.04
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Geek123Password"
    ports:
      - 1433:1433
    volumes:
      - sql-data:/var/opt/mssql
volumes:
  sql-data:
