namespace GeekStore.Domain.Entities;
public class ShoppingCart
{
    // 'Key Id' is generated by client side
    public required string Id { get; set; }
    public List<CartItem> Items { get; set; } = [];
    public int? DeliveryMethodId { get; set; }
    public string? PostalCode { get; set; }
    public string? ClientSecret { get; set; }
    public  string? PaymentIntentId { get; set; }
}
