//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekStore.Domain.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeekStore.Domain.Shared.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error..
        /// </summary>
        public static string DEFAULT_ERROR {
            get {
                return ResourceManager.GetString("DEFAULT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found..
        /// </summary>
        public static string DEFAULT_NOT_FOUND {
            get {
                return ResourceManager.GetString("DEFAULT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product brand is required..
        /// </summary>
        public static string EMPTY_PRODUCT_BRAND {
            get {
                return ResourceManager.GetString("EMPTY_PRODUCT_BRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product description is required..
        /// </summary>
        public static string EMPTY_PRODUCT_DESCRIPTION {
            get {
                return ResourceManager.GetString("EMPTY_PRODUCT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product height is required..
        /// </summary>
        public static string EMPTY_PRODUCT_HEIGHT {
            get {
                return ResourceManager.GetString("EMPTY_PRODUCT_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Id is required..
        /// </summary>
        public static string EMPTY_PRODUCT_ID {
            get {
                return ResourceManager.GetString("EMPTY_PRODUCT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product length is required..
        /// </summary>
        public static string EMPTY_PRODUCT_LENGTH {
            get {
                return ResourceManager.GetString("EMPTY_PRODUCT_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name is required..
        /// </summary>
        public static string EMPTY_PRODUCT_NAME {
            get {
                return ResourceManager.GetString("EMPTY_PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product picture is required..
        /// </summary>
        public static string EMPTY_PRODUCT_PICTURE {
            get {
                return ResourceManager.GetString("EMPTY_PRODUCT_PICTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product price is required..
        /// </summary>
        public static string EMPTY_PRODUCT_PRICE {
            get {
                return ResourceManager.GetString("EMPTY_PRODUCT_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product quantity is required..
        /// </summary>
        public static string EMPTY_PRODUCT_QUANTITY {
            get {
                return ResourceManager.GetString("EMPTY_PRODUCT_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product type is required..
        /// </summary>
        public static string EMPTY_PRODUCT_TYPE {
            get {
                return ResourceManager.GetString("EMPTY_PRODUCT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product weight is required..
        /// </summary>
        public static string EMPTY_PRODUCT_WEIGHT {
            get {
                return ResourceManager.GetString("EMPTY_PRODUCT_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product width is required..
        /// </summary>
        public static string EMPTY_PRODUCT_WIDTH {
            get {
                return ResourceManager.GetString("EMPTY_PRODUCT_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping cart Id is required..
        /// </summary>
        public static string EMPTY_SHOPPING_CART_ID {
            get {
                return ResourceManager.GetString("EMPTY_SHOPPING_CART_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while creating the product!.
        /// </summary>
        public static string ERROR_CREATE_PRODUCT {
            get {
                return ResourceManager.GetString("ERROR_CREATE_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove product..
        /// </summary>
        public static string ERROR_REMOVE_PRODUCT {
            get {
                return ResourceManager.GetString("ERROR_REMOVE_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to persist product in database..
        /// </summary>
        public static string ERROR_UPDATE_PRODUCT {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful operation..
        /// </summary>
        public static string GENERIC_SUCCESS_OPERATION {
            get {
                return ResourceManager.GetString("GENERIC_SUCCESS_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size must be between 1 and 10..
        /// </summary>
        public static string INTERVAL_PAGE_SIZE {
            get {
                return ResourceManager.GetString("INTERVAL_PAGE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product brand must not exceed 100 characters..
        /// </summary>
        public static string MAX_PRODUCT_BRAND {
            get {
                return ResourceManager.GetString("MAX_PRODUCT_BRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product description must not exceed 300 characters..
        /// </summary>
        public static string MAX_PRODUCT_DESCRIPTION {
            get {
                return ResourceManager.GetString("MAX_PRODUCT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name must not exceed 100 characters..
        /// </summary>
        public static string MAX_PRODUCT_NAME {
            get {
                return ResourceManager.GetString("MAX_PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product type must not exceed 100 characters..
        /// </summary>
        public static string MAX_PRODUCT_TYPE {
            get {
                return ResourceManager.GetString("MAX_PRODUCT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page index must be greater than zero..
        /// </summary>
        public static string MIN_PAGE_INDEX {
            get {
                return ResourceManager.GetString("MIN_PAGE_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product height must be greater than zero..
        /// </summary>
        public static string MIN_PRODUCT_HEIGHT {
            get {
                return ResourceManager.GetString("MIN_PRODUCT_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product length must be greater than zero..
        /// </summary>
        public static string MIN_PRODUCT_LENGTH {
            get {
                return ResourceManager.GetString("MIN_PRODUCT_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be greater than zero..
        /// </summary>
        public static string MIN_PRODUCT_PRICE {
            get {
                return ResourceManager.GetString("MIN_PRODUCT_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product quantity cannot be zero or negative..
        /// </summary>
        public static string MIN_PRODUCT_QUANTITY {
            get {
                return ResourceManager.GetString("MIN_PRODUCT_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product weight must be greater than zero..
        /// </summary>
        public static string MIN_PRODUCT_WEIGHT {
            get {
                return ResourceManager.GetString("MIN_PRODUCT_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product width must be greater than zero..
        /// </summary>
        public static string MIN_PRODUCT_WIDTH {
            get {
                return ResourceManager.GetString("MIN_PRODUCT_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Id and url mismatch..
        /// </summary>
        public static string PRODUCT_ID_AND_URL_MISMATCH {
            get {
                return ResourceManager.GetString("PRODUCT_ID_AND_URL_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product was not found..
        /// </summary>
        public static string PRODUCT_NOT_FOUND {
            get {
                return ResourceManager.GetString("PRODUCT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while removing from database..
        /// </summary>
        public static string REMOVE_ERROR {
            get {
                return ResourceManager.GetString("REMOVE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string REQUEST_ERROR {
            get {
                return ResourceManager.GetString("REQUEST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page index is required..
        /// </summary>
        public static string REQUIRED_PAGE_INDEX {
            get {
                return ResourceManager.GetString("REQUIRED_PAGE_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error with shopping cart was happen..
        /// </summary>
        public static string SHOPPING_CART_ERROR {
            get {
                return ResourceManager.GetString("SHOPPING_CART_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given shopping cart cannot be null..
        /// </summary>
        public static string SHOPPING_CART_NULL {
            get {
                return ResourceManager.GetString("SHOPPING_CART_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        public static string UNEXPECTED_ERROR {
            get {
                return ResourceManager.GetString("UNEXPECTED_ERROR", resourceCulture);
            }
        }
    }
}
